In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sb
%matplotlib inline
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
# xData => [공부시간, 과외시간]
temp = [[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]]
print(temp)
print(type(type))
xData = np.array(temp)
print(type(xData))

[[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]]
<class 'type'>
<class 'numpy.ndarray'>


In [6]:
temp = [0, 0, 0, 1, 1, 1, 1]
yData = np.array(temp)
print(yData)
# reshape() : 넘파이에서 데이터는 그대로 유지하고 배열의 형태(차원)만 변경합니다.
yData = np.array(temp).reshape(7, 1)
print(yData)

[0 0 0 1 1 1 1]
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [28]:
X = tf.placeholder(dtype = tf.float32, shape = [None, 2])
Y = tf.placeholder(dtype = tf.float32, shape = [None, 1])

In [29]:
a = tf.Variable(tf.random_uniform([2, 1]), dtype = tf.float32)
b = tf.Variable(tf.random_uniform([1], dtype = tf.float32))
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('{}'.format(sess.run(a)))
print('{}'.format(sess.run(b)))

[[0.875633  ]
 [0.25602376]]
[0.1514504]


In [30]:
# matmul() : tensorflow에서 행렬의 곱셈을 계산하는 메소드
# sigmoid() : tensorflow에서 sigmoid 방정식을 계산하는 메소드
y = tf.sigmoid(tf.matmul(X, a) + b)
loss = -tf.reduce_mean(Y * tf.log(y) + (1-y) * tf.log(1 - y))
gradient_descent = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

In [31]:
# sigmoid() 메소드의 실행 결과(y)가 0.5 이상이면 1을, 0.5 미만이면 0을 리턴시킵니다.
sess = tf.Session()
# 예상값, sigmoid() 메소드를 실행한 결과(y)를 0 또는 1로 변환
# cast() 메소드의 캐스팅할 데이터가 boolean타입이면 True는 1로 False는 0으로 캐스팅됩니다.
predicted = tf.cast(y >= 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.int32))

In [32]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(3001):
    a_, b_, loss_, gradient_descent_ = sess.run([a, b, loss, gradient_descent], feed_dict = {X : xData, Y : yData})
    if i % 300 == 0:
        print('no : %6d, a1 = %7.5f, a2 = %9.5f, b = %9.5f, loss : %.5f' % (i, a_[0], a_[1], b_, loss_))
print('=' * 100)

# 테스트 데이터를 만듭니다.
new_x = np.array([6, 5]).reshape(1, 2)
print(new_x)

# sigmoid() 메소드 연산 결과에 테스트 데이터를 대입하여 연산합니다.
result, new_y = sess.run([predicted, y], feed_dict = {X : new_x})
print("공부 시간 : %d, 과외 시간 : %d" % (new_x[:, 0], new_x[:, 1]))
print("합격 여부(sigmoid() 메소드 실행 결과를 0.5 이상은 1, 미만은 0으로 변환합니다.) : %d, 합격 확률 : %f" %(result, new_y))

for i in range(11):
    new_x = np.array([0, i]).reshape(1, 2)
    result, new_y = sess.run([predicted, y], feed_dict = {X : new_x})
    print('공부시간 : %d, 과외시간 : %2d' %(new_x[:, 0], new_x[:, 1]), end = ', ')
    print('합격 여부 : %s, 합격확률 : %8.4f%%' % ('합격' if result == 1 else '불합격', new_y * 100 ))

no :      0, a1 = 0.42545, a2 =   0.42414, b =   0.01390, loss : 0.07193
no :    300, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :    600, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :    900, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   1200, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   1500, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   1800, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   2100, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   2400, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   2700, a1 =     nan, a2 =       nan, b =       nan, loss : nan
no :   3000, a1 =     nan, a2 =       nan, b =       nan, loss : nan
[[6 5]]
공부 시간 : 6, 과외 시간 : 5
합격 여부(sigmoid() 메소드 실행 결과를 0.5 이상은 1, 미만은 0으로 변환합니다.) : 0, 합격 확률 : nan
공부시간 : 0, 과외시간 :  0, 합격 여부 : 불합격, 합격확률 :      nan%
공부시간 : 0, 과외시간 :  1, 합격 여부 : 불합격, 합격확률 :      nan%
공부시간 : 0, 과외시간 :  2, 합격 여부 : 불합격, 합