In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [4]:
x = np.arange(10).reshape(-1, 1)
y = (2 * x + 1).reshape(-1, 1)

In [5]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [7]:
model = LinearRegression()  # 모델 선언
model

LinearRegression()

In [9]:
model.fit(x, y)    # 입력변수와 출력변수 학습

LinearRegression()

In [10]:
prediction = model.predict([[10.0]])  # 예측

In [11]:
prediction

array([[21.]])